#!/bin/sh
xrandr --output LVDS1 --mode 1600x900 --pos 0x0 --rotate normal
# xrandr --output VGA1 --auto --rotate left --output LVDS1 --left-of VGA1
xrandr --output VGA1 --auto --rotate normal --output LVDS1 --left-of VGA1
# feh --bg-fill ~/pictures/Wallpapers/wallpaper
