#!/bin/bash
# Erandr - Evan's RandR
# Evan Widloski - 2016-11-27
# xrandr shortcuts

# --------- Examples ---------
## place secondary display to the left of primary
# erandr left
#
## place secondary display to the right of primary
# erandr right

## place secondary display to the left of primary, rotate 90
# erandr left vert

## use secondary screen as main monitor, disable primary
# erandr movie

## return to normal single display on primary
# erandr single

# try load displays from config
if [ -f ~/.erandr ]
then
    source ~/.erandr
# otherwise, try to figure out primary and secondary from xrandr output
else
     ## main display name
     primary=$(xrandr | awk '/ connected primary/{print $1}')
     ## secondary display name
     secondary=$(xrandr | awk '/ connected primary/{next}/ connected/{print $1;exit}')
fi

## rotate `secondary` for vertical screens
if [[ $* == *vert* ]]
then
    rotate=left
else
    rotate=normal
fi

## place `secondary` to the right of `primary`
if [[ $* == *right* ]]
then
    xrandr --output $primary --auto --output $secondary --auto --right-of $primary --rotate $rotate
fi

## place `secondary` to the left of `primary`
if [[ $* == *left* ]]
then
    xrandr --output $primary --auto --output $secondary --auto --left-of $primary --rotate $rotate
fi

## reset and go back to single monitor
if [[ $* == *single* ]]
then
    xrandr --output $primary --auto --rotate $rotate --output $secondary --off
fi

## turn off `primary` and turn on `secondary`
if [[ $* == *movie* ]]
then
    xrandr --output $primary --off --output $secondary --auto --rotate $rotate
fi
