#!/usr/bin/env python3
import json
import subprocess
# move all workspaces to other monitor

workspaces = json.loads(
    subprocess.run(
        'i3-msg -t get_workspaces',
        capture_output=True,
        shell=True
    ).stdout
)
output_a, output_b = {w['output'] for w in workspaces}
for w in workspaces:
    other = output_a if w['output'] == output_b else output_b
    subprocess.run(
        'i3-msg \'[workspace="{}"]\' move workspace to output {}'.format(w['name'], other),
        shell=True
    )
