#!/bin/bash
printf "$(date "+%Y-%m-%d_%H:%M") " >> /home/evan/logs/usage.log

filename=$(date "+%Y-%m-%d_%H:%M").jpg
fswebcam -r 640x480 --jpeg 85 -D 2 /home/evan/.cam/$filename
kb_mouse
# chown evan /home/evan/.cam/$filename

# batt_state=$(echo $(acpi -b)|awk '{print $3}')
# if [ "$batt_state" = "Discharging," ]
# then
# 	/etc/acpi/actions/power_management/power_disconnect
# else
# 	/etc/acpi/actions/power_management/power_connect
# fi
