#!/bin/bash
# Evan Widloski
# Radio stations

station_name=("WBAA-AM"
              "WBAA-FM"
              "WBAA-Jazz"
              "WUOT - Public Radio (Knoxville)"
              "WDVX - Bluegrass (Knoxville)"
              "WJEF")
station_urls=("http://evanw.org:8000/wbaa-am.m3u"
              "http://evanw.org:8000/wbaa-fm.m3u"
              "http://purdue.streamguys1.com/wbaa-jazz"
              "http://evanw.org:8000/wuot.m3u"
              "http://wdvx.stream.egihosting.com:8000/?type=http&nocache=53430"
              "http://streamingv2.shoutcast.com/wjef")
file_name=("BBC World News"
           "BBC Science in Action"
           "BBC Tech Tent"
           "BBC News Podcast")
file_urls=($(curl -s "https://podcasts.files.bbci.co.uk/p002vsnk.rss" |grep -Po 'http://[^:\"]+\.mp3'|head -1)
           $(curl -s "https://podcasts.files.bbci.co.uk/p002vsnb.rss" |grep -Po 'http://[^:\"]+\.mp3'|head -1)
           $(curl -s "https://podcasts.files.bbci.co.uk/p01plr2p.rss"|grep -Po 'http://[^:\"]+\.mp3'|head -1)
           $(curl -s "https://podcasts.files.bbci.co.uk/p02nq0gn.rss"|grep -Po 'http://[^:\"]+\.mp3'|head -1))

names=("${station_name[@]}" "${file_name[@]}")
urls=("${station_urls[@]}" "${file_urls[@]}")

printf "Selection a station:\n"

# find biggest string
max=0
IFS=""
for i in ${names[@]}
do
    if [ "${#i}" -gt "$max" ]
    then
        max=${#i}
    fi
done
for((i=0;i<$((${#names[@]}-(${#names[@]}/2)));i++))
do
    # print out options in two columns
    printf "%-$((10+$max))s %-$((10+$max))s\n" "$((2*$i+1))) ${names[$((2*$i))]}" "$((2*$i+2))) ${names[$((2*$i+1))]}"
done

read -n 1 selection

echo ${urls[$((${selection}-1))]}
if ((selection <= ${#station_urls[@]}))
then
    # mpv --no-video -playlist ${urls[$((${selection}-1))]}
    mpv --no-video ${urls[$((${selection}-1))]}
else
    mpv --no-video ${urls[$((${selection}-1))]}
fi
