#!/bin/bash
#Evan Widloski 2014
#simple alsa vol ctrl script

if [ $1 = "up" ]
		then
		curr_vol=$(amixer get 'DAC,1'|grep -Po "(?<=\[)[0-9]+")
		if [ $curr_vol = "0" ]
				then
				amixer set "DAC" 5%;amixer set "DAC,1" 5%
				else
				amixer set "DAC" 2.1+;amixer set "DAC,1" 2.1+
		fi
		else
		amixer set "DAC" 2.1-;amixer set DAC,1 2.1-
fi
