#!/bin/sh

if [ $1 = 'up' ]; then
    pactl set-sink-volume 0 +10%
elif [ $1 = 'down' ]; then
    pactl set-sink-volume 0 -10%
elif [ $1 = 'mute' ]; then
    pactl set-sink-mute 0 toggle
else
    echo "Unknown control command: $1" >&2
    exit 1
fi
